Первая итерация 9ого проекта
ArchieBar/java-filmorate pull request #5
Opened 2024-01-09 16:12 UTC by ArchieBar

Немного не разобрался как отрабатывать правильно исключения с нотациями, и не смог написать тесты под них, если есть какая интересная ссылка почитать - будет круто, либо их лучшее вообще не использовать?

2024-01-09 19:06 UTC, dgumich requested changes

2024-01-09 19:06 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "Email адрес должен быть формата: \"email@email.email\"")
Молодец, что сделал валидацию через спринг!

2024-01-10 11:29 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.BAD_REQUEST);
Исправил, не уверен, что корректно отправлять ответ как Object, но нашёл только такое решение, теперь всё возвращается красиво :)

2024-01-10 11:29 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Вызов POST /films");
Исправил

2024-01-10 11:29 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(film, HttpStatus.NOT_FOUND);
Исправил

2024-01-10 11:31 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getAllFilm() {
Эх, когда-нибудь Английский станет моим вторым родным, но пока перебиваюсь переводчик и уровнем Hello, my name is Artur :)

Исправил

2024-01-10 11:31 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean checkValidityFilm(Film film) throws ValidationException {
Исправил

2024-01-10 11:31 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends IOException {
Исправил

2024-01-10 11:32 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            flag = true;
Поломал голову над валидацией, как-то не подумал, что исключение будет срабатывать :(

Исправил

2024-01-10 11:32 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return flag;
Исправил

2024-01-10 11:39 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Не то чтобы я не доверял спрингу, но я не понимаю как обработать исключение и отправить нужный мне ответ при проверке через @Valid серверу. Код ответа он отправляет, с этим ок, но тело ответа та он не формирует нормальное. А как это сделать в интернете я не нашёл, к тому же не понял как правильно написать внутренний тест для проверки, если создавать просто через метод userController.createUser(), то он пропускает проверку. В общем с этим есть некоторые вопросы

2024-01-10 16:17 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Всё, разобрался :)

2024-01-10 19:58 UTC, dgumich requested changes

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ExceptionHandler(ValidationException.class)
Да, аннотация правильная и так правда делают ловлю исключения. Пока ок оставить так, в следующей задаче лучше вынести в отдельный класс-хендлер. Вот здесь можешь почитать про работу с исключениями https://struchkov.dev/blog/ru/exception-handling-controlleradvice/ и https://www.baeldung.com/exception-handling-for-rest-with-spring

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Object> createFilm(@Valid @RequestBody Film film) {
Не, смотри, нам в принципе на пост не надо отправлять фильм обратно. Смысл его туда-обратно пересылать?=)
Заменяешь ResponseEntity(Object) на ResponseEntity(String) и вместо фильма отправляешь сообщение: все хорошо, фильм добавлен

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Object> updateFilm(@Valid @RequestBody Film film) {
Аналогично и здесь используешь ResponseEntity(String) и сообщения: все ок, обновили или неа, не обновили. Никаких gson нам не нужно=)

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private ResponseEntity<Object> handleMethodArgumentNotValidException(MethodArgumentNotValidException exception) {
И здесь используй  ResponseEntity(String)

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Object> createUser(@Valid @RequestBody User user) {
Здесь так же исправь на строку, а не объект

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Object> updateUser(@Valid @RequestBody User user) {
И здесь=)

2024-01-10 19:58 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private ResponseEntity<Object> handleValidationException(ValidationException exception) {
И здесь

2024-01-11 10:43 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Object> createFilm(@Valid @RequestBody Film film) {
![изображение](https://github.com/ArchieBar/java-filmorate/assets/142429962/2fa678b1-63fb-4033-b5df-7444e17f086e) Если сделать как ты говоришь, то тесты в постмане не пройдут :(

2024-01-12 15:21 UTC, dgumich approved these changes

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Object> createFilm(@Valid @RequestBody Film film) {
Ок, если нужно отправлять обратно фильм - то типизируй ответ ResponseEntity(Film). 
Так будет правильней, обджект не надо оставлять.

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity<>(gson.toJson("Фильм c id: " + film.getId() + " не найден"),
Аналогично, сделай через ResponseEntity(Film), в случае если все удачно - вернешь фильм, а если нет, то просто статус. Пока можешь не заморачиватьсяgson.toJson("Фильм c id: " + film.getId() + " не найден"). Кстати, спринг бут создает много бинов (объектов), которые можно использовать. В том числе и для сериализации/десериализации json. Так что не надо добавлять gson, можно все из коробки=)

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(gson.toJson("Ошибка валидации: " + exception.getMessage()),
gson.toJson тут точно не нужен, просто возвращаешь строку "Ошибка валидации: " + exception.getMessage()

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(gson.toJson("Ошибка валидации: " + exception.getMessage()),
Аналогично и здесь

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Object> createUser(@Valid @RequestBody User user) {
Исправь Object на User

2024-01-12 15:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Object> updateUser(@Valid @RequestBody User user) {
Исправь Object на User

2024-01-12 15:43 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(gson.toJson("Ошибка валидации: " + exception.getMessage()),
Если вернуть просто строку, то тесты в постман не проходят проверку :( 
![изображение](https://github.com/ArchieBar/java-filmorate/assets/142429962/dced1e5b-3a8b-4c4d-91f2-912529071c9d)

2024-01-24 11:23 UTC, merged